# Generated by Django 5.0.7 on 2024-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_restaurant_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
