# Generated by Django 5.0.7 on 2024-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_restaurant_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
